package consts

const Revision = "171"

const WasmVersion = 37

//const MOUSE = { LEFT: 0, MIDDLE: 1, RIGHT: 2, ROTATE: 0, DOLLY: 1, PAN: 2 };
//const TOUCH = { ROTATE: 0, PAN: 1, DOLLY_PAN: 2, DOLLY_ROTATE: 3 };
//const BasicShadowMap = 0;
//const PCFShadowMap = 1;
//const PCFSoftShadowMap = 2;
//const VSMShadowMap = 3;
//const FrontSide = 0;
//const BackSide = 1;
//const DoubleSide = 2;
//const NoBlending = 0;
//const NormalBlending = 1;
//const AdditiveBlending = 2;
//const SubtractiveBlending = 3;
//const MultiplyBlending = 4;
//const CustomBlending = 5;
//const AddEquation = 100;
//const SubtractEquation = 101;
//const ReverseSubtractEquation = 102;
//const MinEquation = 103;
//const MaxEquation = 104;
//const ZeroFactor = 200;
//const OneFactor = 201;
//const SrcColorFactor = 202;
//const OneMinusSrcColorFactor = 203;
//const SrcAlphaFactor = 204;
//const OneMinusSrcAlphaFactor = 205;
//const DstAlphaFactor = 206;
//const OneMinusDstAlphaFactor = 207;
//const DstColorFactor = 208;
//const OneMinusDstColorFactor = 209;
//const SrcAlphaSaturateFactor = 210;
//const ConstantColorFactor = 211;
//const OneMinusConstantColorFactor = 212;
//const ConstantAlphaFactor = 213;
//const OneMinusConstantAlphaFactor = 214;
//const NeverDepth = 0;
//const AlwaysDepth = 1;
//const LessDepth = 2;
//const LessEqualDepth = 3;
//const EqualDepth = 4;
//const GreaterEqualDepth = 5;
//const GreaterDepth = 6;
//const NotEqualDepth = 7;
//const MultiplyOperation = 0;
//const MixOperation = 1;
//const AddOperation = 2;
//const NoToneMapping = 0;
//const LinearToneMapping = 1;
//const ReinhardToneMapping = 2;
//const CineonToneMapping = 3;
//const ACESFilmicToneMapping = 4;
//const CustomToneMapping = 5;
//const AgXToneMapping = 6;
//const NeutralToneMapping = 7;
//const AttachedBindMode = 'attached';
//const DetachedBindMode = 'detached';
//
//const UVMapping = 300;
//const CubeReflectionMapping = 301;
//const CubeRefractionMapping = 302;
//const EquirectangularReflectionMapping = 303;
//const EquirectangularRefractionMapping = 304;
//const CubeUVReflectionMapping = 306;
//const RepeatWrapping = 1000;
//const ClampToEdgeWrapping = 1001;
//const MirroredRepeatWrapping = 1002;
//const NearestFilter = 1003;
//const NearestMipmapNearestFilter = 1004;
//const NearestMipMapNearestFilter = 1004;
//const NearestMipmapLinearFilter = 1005;
//const NearestMipMapLinearFilter = 1005;
//const LinearFilter = 1006;
//const LinearMipmapNearestFilter = 1007;
//const LinearMipMapNearestFilter = 1007;
//const LinearMipmapLinearFilter = 1008;
//const LinearMipMapLinearFilter = 1008;

//const LoopOnce = 2200;
//const LoopRepeat = 2201;
//const LoopPingPong = 2202;
//const InterpolateDiscrete = 2300;
//const InterpolateLinear = 2301;
//const InterpolateSmooth = 2302;
//const ZeroCurvatureEnding = 2400;
//const ZeroSlopeEnding = 2401;
//const WrapAroundEnding = 2402;
//const NormalAnimationBlendMode = 2500;
//const AdditiveAnimationBlendMode = 2501;
//const TrianglesDrawMode = 0;
//const TriangleStripDrawMode = 1;
//const TriangleFanDrawMode = 2;
//const BasicDepthPacking = 3200;
//const RGBADepthPacking = 3201;
//const RGBDepthPacking = 3202;
//const RGDepthPacking = 3203;
//const TangentSpaceNormalMap = 0;
//const ObjectSpaceNormalMap = 1;
//
//const ZeroStencilOp = 0;
//const KeepStencilOp = 7680;
//const ReplaceStencilOp = 7681;
//const IncrementStencilOp = 7682;
//const DecrementStencilOp = 7683;
//const IncrementWrapStencilOp = 34055;
//const DecrementWrapStencilOp = 34056;
//const InvertStencilOp = 5386;
//
//const NeverStencilFunc = 512;
//const LessStencilFunc = 513;
//const EqualStencilFunc = 514;
//const LessEqualStencilFunc = 515;
//const GreaterStencilFunc = 516;
//const NotEqualStencilFunc = 517;
//const GreaterEqualStencilFunc = 518;
//const AlwaysStencilFunc = 519;
//
//const NeverCompare = 512;
//const LessCompare = 513;
//const EqualCompare = 514;
//const LessEqualCompare = 515;
//const GreaterCompare = 516;
//const NotEqualCompare = 517;
//const GreaterEqualCompare = 518;
//const AlwaysCompare = 519;
//
//const StaticDrawUsage = 35044;
//const DynamicDrawUsage = 35048;
//const StreamDrawUsage = 35040;
//const StaticReadUsage = 35045;
//const DynamicReadUsage = 35049;
//const StreamReadUsage = 35041;
//const StaticCopyUsage = 35046;
//const DynamicCopyUsage = 35050;
//const StreamCopyUsage = 35042;
//
//const GLSL1 = '100';
//const GLSL3 = '300 es';
//
//const WebGLCoordinateSystem = 2000;
//const WebGPUCoordinateSystem = 2001;
